#!/usr/bin/env python3
"""
gen_shim.py — read j2534_interface.dll exports and emit:
    src/j2534_interface.def    — module-definition file
    src/forwarders.c           — naked-jmp forwarder stubs for non-instrumented exports

Mirror of cstech2win/scripts/gen_shim.py but for the J2534 PassThru API.

Run: python3 gen_shim.py /path/to/CHIPSOFT_J2534_Pro_Driver/j2534_interface.dll
"""
import argparse, sys
from pathlib import Path

try:
    import pefile
except ImportError:
    print("ERROR: pip install pefile", file=sys.stderr); sys.exit(2)

INSTRUMENTED = {
    "PassThruOpen",
    "PassThruConnect",
    "PassThruIoctl",
    "PassThruStartMsgFilter",
    "PassThruWriteMsgs",
    "PassThruReadMsgs",
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("dll", help="Path to real j2534_interface.dll")
    ap.add_argument("--out-dir", default=None,
                    help="Output dir (default: ../src/)")
    args = ap.parse_args()

    out_dir = Path(args.out_dir) if args.out_dir else Path(__file__).parent.parent / "src"
    out_dir.mkdir(parents=True, exist_ok=True)

    pe = pefile.PE(args.dll)
    if not hasattr(pe, "DIRECTORY_ENTRY_EXPORT"):
        print(f"ERROR: {args.dll} has no export table", file=sys.stderr)
        return 1

    exports = []
    for e in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if not e.name:
            continue
        exports.append((e.ordinal, e.name.decode()))
    exports.sort(key=lambda x: x[0])

    if pe.FILE_HEADER.Machine != 0x14c:
        print(f"WARN: machine type 0x{pe.FILE_HEADER.Machine:04x} is not x86; "
              f"shim assumes 32-bit", file=sys.stderr)

    print(f"Read {len(exports)} exports from {args.dll}")

    # 1. .def file
    def_path = out_dir / "j2534_interface.def"
    with def_path.open("w", encoding="utf-8") as f:
        f.write("; Auto-generated by gen_shim.py — DO NOT EDIT BY HAND\n")
        f.write("LIBRARY j2534_interface\n")
        f.write("EXPORTS\n")
        for ordinal, name in exports:
            f.write(f"    {name:<32}@{ordinal}\n")
    print(f"  wrote {def_path}")

    # 2. forwarders.c
    fwd_path = out_dir / "forwarders.c"
    passthrough = [(o, n) for o, n in exports if n not in INSTRUMENTED]
    with fwd_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by gen_shim.py — DO NOT EDIT BY HAND\n")
        f.write("// Naked-jmp forwarders for J2534 exports we don't instrument.\n\n")
        f.write('#include "shim.h"\n\n')
        for ordinal, name in passthrough:
            f.write(f"FARPROC g_real_{name} = NULL;\n")
        f.write("\n")
        f.write("void resolve_passthrough_exports(HMODULE hReal) {\n")
        for ordinal, name in passthrough:
            f.write(f'    g_real_{name} = GetProcAddress(hReal, "{name}");\n')
        f.write("}\n\n")
        for ordinal, name in passthrough:
            f.write(f"// {name} (ord {ordinal}) — naked forwarder\n")
            f.write(f"__attribute__((naked)) void {name}(void) {{\n")
            f.write(f"    __asm__ __volatile__ (\n")
            f.write(f'        "jmp *%0\\n"\n')
            f.write(f'        : : "m" (g_real_{name})\n')
            f.write(f"    );\n")
            f.write(f"}}\n\n")
    print(f"  wrote {fwd_path} ({len(passthrough)} forwarders)")

    print()
    print(f"Total exports     : {len(exports)}")
    print(f"  Forwarders      : {len(passthrough)}")
    print(f"  Instrumented    : {len(INSTRUMENTED)} (hand-written in src/wrappers.c)")
    missing = INSTRUMENTED - {n for _, n in exports}
    if missing:
        print(f"\n  WARNING: instrumented names NOT in DLL: {missing}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
