// Round 6: dump every function that reads an options.json key, plus the
// log-path construction site, plus all callers of boost::property_tree json
// readers. Together these answer:
//   - LogLevel scale (what value enables, what disables)
//   - Default log file path (where \logs\ + %Y%m%d_%H%M%S.log lands)
//   - Full set of options.json keys + their defaults
//
// Strategy: enumerate every reference to each interesting string constant
// (LogLevel, options.json, the tier names, etc.), collect the containing
// functions, and dump their decompiled bodies. The decompile shows the
// `if (value <= N) return;` log-suppression check, the path-concat sequence,
// and any other property keys read in the same scope.
//
// @category Chipsoft_RE
// @runtime Java

import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressIterator;
import ghidra.program.model.data.StringDataInstance;
import ghidra.program.model.listing.Data;
import ghidra.program.model.listing.DataIterator;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;
import ghidra.program.model.listing.Listing;
import ghidra.program.model.listing.Program;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.ReferenceIterator;
import ghidra.program.model.symbol.ReferenceManager;
import ghidra.program.model.mem.Memory;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

public class DumpConfig extends GhidraScript {

    // Strings to chase. These are the ones surfaced by `strings(1)` near the
    // options.json constant (offsets 0xdf8d4..0xdfdec in the .rdata blob).
    private static final String[] NEEDLES = {
        "LogLevel",
        "options.json",
        "OpenPort2Mode",
        "RemapAUXToPIN",
        "SplitReadTimeout",
        "Lite",
        "Mid",
        "Pro",
        "\\logs\\",
        "%Y%m%d_%H%M%S.log",
        "[%TimeStamp%]: %Message%",
        "CHIPSOFT_J2534",
        "Severity",
    };

    @Override
    protected void run() throws Exception {
        Program program = currentProgram;
        FunctionManager fm = program.getFunctionManager();
        ReferenceManager rm = program.getReferenceManager();
        Listing listing = program.getListing();
        Memory mem = program.getMemory();

        String outPath = System.getenv("GHIDRA_DUMP_OUT");
        if (outPath == null) outPath = program.getExecutablePath() + ".config.md";
        PrintWriter out = new PrintWriter(new FileWriter(new File(outPath)));

        out.println("# Ghidra config dump — options.json readers + log-path construction");
        out.println();
        out.println("Generated by `tools/ghidra_scripts/DumpConfig.java`.");
        out.println("Image base: 0x" + Long.toHexString(program.getImageBase().getOffset()));
        out.println();

        // ---------------------------------------------------------------------
        // 1. Locate each needle string in the data sections.
        // ---------------------------------------------------------------------
        Map<String, List<Address>> needleAddrs = new LinkedHashMap<>();
        for (String s : NEEDLES) needleAddrs.put(s, new ArrayList<>());

        DataIterator dit = listing.getDefinedData(true);
        while (dit.hasNext()) {
            Data d = dit.next();
            if (!d.hasStringValue()) continue;
            StringDataInstance sdi = StringDataInstance.getStringDataInstance(d);
            if (sdi == null) continue;
            String v = sdi.getStringValue();
            if (v == null) continue;
            for (String n : NEEDLES) {
                if (v.equals(n)) {
                    needleAddrs.get(n).add(d.getAddress());
                }
            }
        }

        out.println("## String locations");
        out.println();
        out.println("| Needle | Found at |");
        out.println("|---|---|");
        for (String n : NEEDLES) {
            List<Address> as = needleAddrs.get(n);
            if (as.isEmpty()) {
                out.println("| `" + n + "` | _(not found as defined string)_ |");
            } else {
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < as.size(); i++) {
                    if (i > 0) sb.append(", ");
                    sb.append("0x").append(as.get(i));
                }
                out.println("| `" + n + "` | " + sb + " |");
            }
        }
        out.println();

        // ---------------------------------------------------------------------
        // 2. Collect every function that references any needle.
        //    Track which needles each function references.
        // ---------------------------------------------------------------------
        Map<Long, Function> funcs = new TreeMap<>();
        Map<Long, Set<String>> funcNeedles = new TreeMap<>();
        for (Map.Entry<String, List<Address>> e : needleAddrs.entrySet()) {
            for (Address a : e.getValue()) {
                ReferenceIterator rit = rm.getReferencesTo(a);
                while (rit.hasNext()) {
                    Reference r = rit.next();
                    Function f = fm.getFunctionContaining(r.getFromAddress());
                    if (f == null) continue;
                    long entry = f.getEntryPoint().getOffset();
                    funcs.put(entry, f);
                    funcNeedles.computeIfAbsent(entry, k -> new LinkedHashSet<>()).add(e.getKey());
                }
            }
        }

        out.println("## Functions that reference any of these strings");
        out.println();
        out.println("| Function | Needles referenced |");
        out.println("|---|---|");
        for (long e : funcs.keySet()) {
            Function f = funcs.get(e);
            Set<String> ns = funcNeedles.get(e);
            StringBuilder sb = new StringBuilder();
            for (String n : ns) {
                if (sb.length() > 0) sb.append(", ");
                sb.append("`").append(n).append("`");
            }
            out.println("| " + f.getName() + " @ 0x" + Long.toHexString(e) + " | " + sb + " |");
        }
        out.println();

        // ---------------------------------------------------------------------
        // 3. Decompile each. The interesting cases are:
        //    - Function holding `options.json` (the JSON open + read site)
        //    - Function holding `LogLevel` (the threshold check)
        //    - Function holding `\logs\` (the path build)
        //    - Functions holding tier names `Lite`/`Mid`/`Pro` (probable
        //      device-tier conditional defaults)
        // ---------------------------------------------------------------------
        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(program);

        out.println("## Decompiled bodies");
        out.println();
        for (long e : funcs.keySet()) {
            Function f = funcs.get(e);
            Set<String> ns = funcNeedles.get(e);
            out.println("### " + f.getName() + " @ 0x" + Long.toHexString(e));
            out.println();
            out.println("Refs: " + String.join(", ", ns));
            out.println();

            // List string-data refs from inside this function (helps spot
            // additional config keys we missed in NEEDLES).
            out.println("**All string literals referenced from this function (max 40):**");
            int strs = 0;
            AddressIterator ait = f.getBody().getAddresses(true);
            Set<String> seen = new LinkedHashSet<>();
            while (ait.hasNext() && strs < 40) {
                Address ax = ait.next();
                Reference[] refs = rm.getReferencesFrom(ax);
                for (Reference r : refs) {
                    Data d = listing.getDataAt(r.getToAddress());
                    if (d == null || !d.hasStringValue()) continue;
                    StringDataInstance sdi = StringDataInstance.getStringDataInstance(d);
                    if (sdi == null) continue;
                    String v = sdi.getStringValue();
                    if (v == null || v.isEmpty()) continue;
                    if (seen.add(v)) {
                        out.println("- 0x" + ax + " → `" +
                                v.replace("\n", "\\n").replace("\r", "\\r") + "`");
                        if (++strs >= 40) break;
                    }
                }
            }
            if (strs == 0) out.println("- _(none)_");
            out.println();

            DecompileResults dr = decomp.decompileFunction(f, 90, monitor);
            out.println("```c");
            if (dr != null && dr.getDecompiledFunction() != null) {
                out.println(dr.getDecompiledFunction().getC());
            } else {
                out.println("// decompile failed");
            }
            out.println("```");
            out.println();
        }

        out.close();
        println("[config] wrote " + outPath);
    }
}
