// Round 5: opcode map for FUN_1001d270 (send_and_wait).
//
// FUN_1001d270 is the dispatch entry that frames a request, hands it to the
// IOCP write thread, and blocks on a reply. Its second argument is the
// 32-bit opcode that gets stamped into the wire envelope (see
// `notes/2026-05-05-ghidra-{transport,envelope,drain}.md`).
//
// This script:
//   1. Resolves every PassThru* export thunk to its `_impl` entry point.
//   2. BFS-walks down the call graph from each `_impl` (max depth 6) to
//      collect all functions transitively reachable from that PassThru*.
//   3. Finds every direct caller of FUN_1001d270 and, for each caller,
//      extracts the literal opcode (param_1) and length expression (param_3)
//      from the decompiled C source.
//   4. For each direct caller, walks UP the call graph (max depth 6) to find
//      which PassThru* `_impl` is the entry point that ultimately drives it.
//   5. Emits a markdown table mapping
//      `PassThru* -> wrapper FUN -> opcode (hex) -> length expr`.
//
// @category Chipsoft_RE
// @runtime Java
//
// Output: $GHIDRA_DUMP_OUT, defaulting to <executable>.opcodes.md.

import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;
import ghidra.program.model.listing.Instruction;
import ghidra.program.model.listing.Listing;
import ghidra.program.model.listing.Program;
import ghidra.program.model.symbol.Reference;
import ghidra.program.model.symbol.ReferenceIterator;
import ghidra.program.model.symbol.ReferenceManager;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class DumpOpcodes extends GhidraScript {

    // FUN_1001d270 — send_and_wait. Offset from image base.
    private static final long SEND_AND_WAIT_OFFSET = 0x1d270L;

    // BFS depth caps. Six is enough to cross PassThru -> wrapper -> framer -> dispatcher.
    private static final int DOWN_DEPTH = 6;
    private static final int UP_DEPTH = 6;

    // PassThru* exports — RVA of the export entry (thunk that JMPs to _impl).
    // Recovered manually from the j2534_interface.dll PE export table; see
    // `notes/2026-05-05-ghidra-j2534.md`.
    private static final String[][] PASSTHRU_EXPORTS = {
        {"PassThruOpen",                  "29b0"},
        {"PassThruClose",                 "29c0"},
        {"PassThruConnect",               "2af0"},
        {"PassThruDisconnect",            "2b00"},
        {"PassThruReadMsgs",              "2b10"},
        {"PassThruWriteMsgs",             "2b20"},
        {"PassThruStartPeriodicMsg",      "2b30"},
        {"PassThruStopPeriodicMsg",       "2b40"},
        {"PassThruStartMsgFilter",        "2c30"},
        {"PassThruStopMsgFilter",         "2c40"},
        {"PassThruSetProgrammingVoltage", "2d10"},
        {"PassThruReadVersion",           "2dd0"},
        {"PassThruGetLastError",          "2de0"},
        {"PassThruIoctl",                 "2e80"},
    };

    // Capture the first six args of FUN_1001d270(this, opcode, msg, len, out, timeout).
    private static final Pattern CALL_RE = Pattern.compile(
        "FUN_1001d270\\s*\\(\\s*([^,]+),\\s*([^,]+),\\s*([^,]+),\\s*([^,]+),\\s*([^,]+),\\s*([^)]+)\\)"
    );

    @Override
    protected void run() throws Exception {
        Program program = currentProgram;
        long base = program.getImageBase().getOffset();
        FunctionManager fm = program.getFunctionManager();
        ReferenceManager rm = program.getReferenceManager();
        Listing listing = program.getListing();

        String outPath = System.getenv("GHIDRA_DUMP_OUT");
        if (outPath == null) outPath = program.getExecutablePath() + ".opcodes.md";
        PrintWriter out = new PrintWriter(new FileWriter(new File(outPath)));

        Address sendAndWait = addr(base + SEND_AND_WAIT_OFFSET);

        out.println("# Ghidra opcode map — FUN_1001d270 (send_and_wait)");
        out.println();
        out.println("Generated by `tools/ghidra_scripts/DumpOpcodes.java`.");
        out.println("Image base: 0x" + Long.toHexString(base) +
                    " — send_and_wait: 0x" + Long.toHexString(sendAndWait.getOffset()));
        out.println();

        // ---------------------------------------------------------------------
        // 1. Resolve PassThru export thunks → _impl entries.
        // ---------------------------------------------------------------------
        Map<Long, String> implToName = new LinkedHashMap<>();   // _impl entry -> "PassThruXxx"
        Map<String, Long> nameToImpl = new LinkedHashMap<>();
        out.println("## PassThru export → _impl resolution");
        out.println();
        out.println("| Export | Thunk addr | _impl addr |");
        out.println("|---|---|---|");
        for (String[] exp : PASSTHRU_EXPORTS) {
            long thunkVA = base + Long.parseLong(exp[1], 16);
            long implVA = followFirstJmp(addr(thunkVA));
            implToName.put(implVA, exp[0]);
            nameToImpl.put(exp[0], implVA);
            out.println("| " + exp[0] +
                        " | 0x" + Long.toHexString(thunkVA) +
                        " | 0x" + Long.toHexString(implVA) + " |");
        }
        out.println();

        // ---------------------------------------------------------------------
        // 2. Direct callers of FUN_1001d270.
        // ---------------------------------------------------------------------
        Map<Long, Function> direct = new TreeMap<>();
        ReferenceIterator it = rm.getReferencesTo(sendAndWait);
        while (it.hasNext()) {
            Reference r = it.next();
            Function caller = fm.getFunctionContaining(r.getFromAddress());
            if (caller == null) continue;
            direct.put(caller.getEntryPoint().getOffset(), caller);
        }

        // ---------------------------------------------------------------------
        // 3. For each direct caller, decompile and harvest opcodes (param_1)
        //    and length expressions (param_3).
        // ---------------------------------------------------------------------
        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(program);

        // caller entry -> list of [opcode literal, length expr, full call snippet]
        Map<Long, List<String[]>> opcodesByCaller = new LinkedHashMap<>();
        Map<Long, String> decompCache = new LinkedHashMap<>();
        for (long entry : direct.keySet()) {
            Function f = direct.get(entry);
            DecompileResults dr = decomp.decompileFunction(f, 90, monitor);
            String src = (dr != null && dr.getDecompiledFunction() != null)
                ? dr.getDecompiledFunction().getC()
                : "";
            decompCache.put(entry, src);
            List<String[]> hits = new ArrayList<>();
            Matcher m = CALL_RE.matcher(src);
            while (m.find()) {
                String opcode = m.group(2).trim();
                String lenExpr = m.group(4).trim();
                String full = m.group(0);
                hits.add(new String[]{opcode, lenExpr, full});
            }
            if (hits.isEmpty()) hits.add(new String[]{"(literal not found)", "", ""});
            opcodesByCaller.put(entry, hits);
        }

        // ---------------------------------------------------------------------
        // 4. BFS up from each direct caller until we hit a PassThru *_impl.
        // ---------------------------------------------------------------------
        Map<Long, List<String>> ancestorPassThru = new LinkedHashMap<>();
        for (long entry : direct.keySet()) {
            ancestorPassThru.put(entry, bfsUpToPassThru(entry, implToName, fm, rm));
        }

        // ---------------------------------------------------------------------
        // 5. BFS down from each PassThru _impl to confirm reachability of
        //    each direct caller (orthogonal evidence — guards against the
        //    upward BFS hitting indirect call sites first).
        // ---------------------------------------------------------------------
        Map<String, Set<Long>> passThruReaches = new LinkedHashMap<>();  // PassThru -> set of direct-caller entries reached
        for (Map.Entry<String, Long> ep : nameToImpl.entrySet()) {
            Set<Long> reachableCallers = bfsDownReachable(ep.getValue(), direct.keySet(), fm, listing);
            passThruReaches.put(ep.getKey(), reachableCallers);
        }

        // ---------------------------------------------------------------------
        // 6. Emit the headline table.
        // ---------------------------------------------------------------------
        out.println("## Opcode map — direct FUN_1001d270 callers");
        out.println();
        out.println("Each row is a function that directly invokes `FUN_1001d270`.");
        out.println("`Opcodes` lists every literal seen in `param_1` of any call site");
        out.println("inside that function (one wrapper usually = one opcode).");
        out.println();
        out.println("| Wrapper fn | Opcodes (param_1) | Length expr (param_3) | Reaches up to | Reached down from |");
        out.println("|---|---|---|---|---|");
        for (long entry : direct.keySet()) {
            Function f = direct.get(entry);
            List<String[]> hits = opcodesByCaller.get(entry);
            Set<String> opcodes = new LinkedHashSet<>();
            Set<String> lens = new LinkedHashSet<>();
            for (String[] h : hits) {
                opcodes.add("`" + h[0] + "`");
                if (!h[1].isEmpty()) lens.add("`" + h[1] + "`");
            }
            List<String> upHits = ancestorPassThru.get(entry);
            String up = upHits == null || upHits.isEmpty()
                ? "_(no PassThru in " + UP_DEPTH + " hops)_"
                : String.join(", ", upHits);
            List<String> downHits = new ArrayList<>();
            for (Map.Entry<String, Set<Long>> ep : passThruReaches.entrySet()) {
                if (ep.getValue().contains(entry)) downHits.add(ep.getKey());
            }
            String down = downHits.isEmpty()
                ? "_(unreachable from any PassThru)_"
                : String.join(", ", downHits);
            out.println("| " + f.getName() + " @ 0x" + Long.toHexString(entry) +
                        " | " + String.join(", ", opcodes) +
                        " | " + String.join(", ", lens.isEmpty() ? List.of("`(none)`") : lens) +
                        " | " + up +
                        " | " + down + " |");
        }
        out.println();

        // ---------------------------------------------------------------------
        // 7. Reverse-pivot table: PassThru -> opcodes it ultimately fires.
        // ---------------------------------------------------------------------
        out.println("## PassThru* → opcode set (reverse pivot)");
        out.println();
        out.println("| PassThru export | Opcodes fired | Wrapper fns |");
        out.println("|---|---|---|");
        for (Map.Entry<String, Set<Long>> ep : passThruReaches.entrySet()) {
            Set<String> opSet = new LinkedHashSet<>();
            Set<String> fnSet = new LinkedHashSet<>();
            for (long entry : ep.getValue()) {
                Function f = direct.get(entry);
                if (f == null) continue;
                fnSet.add(f.getName() + " @ 0x" + Long.toHexString(entry));
                for (String[] h : opcodesByCaller.get(entry)) opSet.add("`" + h[0] + "`");
            }
            out.println("| " + ep.getKey() +
                        " | " + (opSet.isEmpty() ? "_(none)_" : String.join(", ", opSet)) +
                        " | " + (fnSet.isEmpty() ? "_(none)_" : String.join("<br>", fnSet)) + " |");
        }
        out.println();

        // ---------------------------------------------------------------------
        // 8. Snippets for each direct caller — helpful when manually
        //    verifying ambiguous cases.
        // ---------------------------------------------------------------------
        out.println("## Call snippets — direct callers");
        out.println();
        for (long entry : direct.keySet()) {
            Function f = direct.get(entry);
            out.println("### " + f.getName() + " @ 0x" + Long.toHexString(entry));
            out.println();
            for (String[] h : opcodesByCaller.get(entry)) {
                if (h[2].isEmpty()) continue;
                out.println("```c");
                out.println(h[2]);
                out.println("```");
            }
            out.println();
        }

        out.close();
        println("[opcodes] wrote " + outPath);
    }

    // ============================================================
    // Helpers.
    // ============================================================

    private Address addr(long va) {
        return currentProgram.getAddressFactory().getDefaultAddressSpace().getAddress(va);
    }

    /**
     * If the function at `from` starts with a `JMP <target>` (the typical
     * PE export thunk pattern), return target offset. Otherwise return
     * `from.getOffset()` so the caller falls back to treating the export as
     * its own _impl.
     */
    private long followFirstJmp(Address from) {
        Listing l = currentProgram.getListing();
        Instruction insn = l.getInstructionAt(from);
        for (int i = 0; i < 4 && insn != null; i++) {
            String mn = insn.getMnemonicString();
            if (mn != null && mn.equalsIgnoreCase("JMP")) {
                Reference[] refs = insn.getReferencesFrom();
                for (Reference r : refs) {
                    if (r.getReferenceType().isJump() ||
                        r.getReferenceType().isCall() ||
                        r.getReferenceType().isFlow()) {
                        return r.getToAddress().getOffset();
                    }
                }
            }
            insn = insn.getNext();
        }
        return from.getOffset();
    }

    /**
     * BFS upward through the caller graph from `start` until a function whose
     * entry is in `implToName` is found, or the depth cap is hit. Returns the
     * unique PassThru names hit (could be more than one for shared utilities).
     */
    private List<String> bfsUpToPassThru(long start,
                                         Map<Long, String> implToName,
                                         FunctionManager fm,
                                         ReferenceManager rm) {
        Set<Long> visited = new HashSet<>();
        Deque<Long> q = new ArrayDeque<>();
        q.add(start);
        visited.add(start);
        Set<String> hits = new LinkedHashSet<>();
        for (int depth = 0; depth < UP_DEPTH; depth++) {
            int n = q.size();
            if (n == 0) break;
            for (int i = 0; i < n; i++) {
                long cur = q.poll();
                if (implToName.containsKey(cur)) hits.add(implToName.get(cur));
                ReferenceIterator rit = rm.getReferencesTo(addr(cur));
                while (rit.hasNext()) {
                    Reference r = rit.next();
                    Function p = fm.getFunctionContaining(r.getFromAddress());
                    if (p == null) continue;
                    long pe = p.getEntryPoint().getOffset();
                    if (visited.add(pe)) q.add(pe);
                }
            }
            if (!hits.isEmpty()) break;
        }
        return new ArrayList<>(hits);
    }

    /**
     * BFS downward (function callees) from `root`, returning the subset of
     * `targets` reached within DOWN_DEPTH hops.
     */
    private Set<Long> bfsDownReachable(long root,
                                       Set<Long> targets,
                                       FunctionManager fm,
                                       Listing listing) {
        Set<Long> visited = new HashSet<>();
        Deque<Long> q = new ArrayDeque<>();
        Set<Long> reached = new HashSet<>();
        q.add(root);
        visited.add(root);
        for (int depth = 0; depth < DOWN_DEPTH; depth++) {
            int n = q.size();
            if (n == 0) break;
            for (int i = 0; i < n; i++) {
                long cur = q.poll();
                if (targets.contains(cur)) reached.add(cur);
                Function f = fm.getFunctionAt(addr(cur));
                if (f == null) continue;
                Set<Function> callees = f.getCalledFunctions(monitor);
                for (Function c : callees) {
                    long ce = c.getEntryPoint().getOffset();
                    if (visited.add(ce)) q.add(ce);
                }
            }
        }
        return reached;
    }
}
