// Auto-generated by gen_shim.py — DO NOT EDIT BY HAND
// Naked-jmp forwarders for J2534 exports we don't instrument.

#include "shim.h"

FARPROC g_real_PassThruClose = NULL;
FARPROC g_real_PassThruDisconnect = NULL;
FARPROC g_real_PassThruGetLastError = NULL;
FARPROC g_real_PassThruReadVersion = NULL;
FARPROC g_real_PassThruSetProgrammingVoltage = NULL;
FARPROC g_real_PassThruStartPeriodicMsg = NULL;
FARPROC g_real_PassThruStopMsgFilter = NULL;
FARPROC g_real_PassThruStopPeriodicMsg = NULL;

void resolve_passthrough_exports(HMODULE hReal) {
    g_real_PassThruClose = GetProcAddress(hReal, "PassThruClose");
    g_real_PassThruDisconnect = GetProcAddress(hReal, "PassThruDisconnect");
    g_real_PassThruGetLastError = GetProcAddress(hReal, "PassThruGetLastError");
    g_real_PassThruReadVersion = GetProcAddress(hReal, "PassThruReadVersion");
    g_real_PassThruSetProgrammingVoltage = GetProcAddress(hReal, "PassThruSetProgrammingVoltage");
    g_real_PassThruStartPeriodicMsg = GetProcAddress(hReal, "PassThruStartPeriodicMsg");
    g_real_PassThruStopMsgFilter = GetProcAddress(hReal, "PassThruStopMsgFilter");
    g_real_PassThruStopPeriodicMsg = GetProcAddress(hReal, "PassThruStopPeriodicMsg");
}

// PassThruClose (ord 1) — naked forwarder
__declspec(naked) void PassThruClose(void) {
    __asm { jmp dword ptr [g_real_PassThruClose] }
}

// PassThruDisconnect (ord 3) — naked forwarder
__declspec(naked) void PassThruDisconnect(void) {
    __asm { jmp dword ptr [g_real_PassThruDisconnect] }
}

// PassThruGetLastError (ord 4) — naked forwarder
__declspec(naked) void PassThruGetLastError(void) {
    __asm { jmp dword ptr [g_real_PassThruGetLastError] }
}

// PassThruReadVersion (ord 8) — naked forwarder
__declspec(naked) void PassThruReadVersion(void) {
    __asm { jmp dword ptr [g_real_PassThruReadVersion] }
}

// PassThruSetProgrammingVoltage (ord 9) — naked forwarder
__declspec(naked) void PassThruSetProgrammingVoltage(void) {
    __asm { jmp dword ptr [g_real_PassThruSetProgrammingVoltage] }
}

// PassThruStartPeriodicMsg (ord 11) — naked forwarder
__declspec(naked) void PassThruStartPeriodicMsg(void) {
    __asm { jmp dword ptr [g_real_PassThruStartPeriodicMsg] }
}

// PassThruStopMsgFilter (ord 12) — naked forwarder
__declspec(naked) void PassThruStopMsgFilter(void) {
    __asm { jmp dword ptr [g_real_PassThruStopMsgFilter] }
}

// PassThruStopPeriodicMsg (ord 13) — naked forwarder
__declspec(naked) void PassThruStopPeriodicMsg(void) {
    __asm { jmp dword ptr [g_real_PassThruStopPeriodicMsg] }
}

